### ISSUE TITLE
q: basic workflow info/example?

### ISSUE THREAD

**Issue by dvdplm** [PLSysSec/haybale-pitchfork#1]
This looks super interesting, and kudos for the great docs. 
I have a question about what the intended/best workflow is for using this. 

Is the idea to run the analysis as a test? I.e. should the analysis code run as tests and then:

1. build the project to emit bc/ir
1. run tests that asserts constant time (or whatever analysis is desired)

Is there any way of automating the first step?

**Comment by cdisselkoen** [comment]
Thanks for your interest!  Yes, conceptually you could run `pitchfork`'s analysis as tests.

For analyzing Rust code, you can emit LLVM bitcode for an entire crate by using
```
RUSTFLAGS=--emit=llvm-bc cargo build --release
```
To also get debuginfo, I recommend temporarily adding the following to your Cargo.toml:
```
[profile.release]
debug = true
```
The bitcode files are generated in `target/release/deps` - one for the toplevel crate and one for each of its dependencies.  To get LLVM IR (text-format) files directly, you can run `llvm-dis` on the bitcode files (that's a tool which ships with LLVM).

For C/C++ projects, rather than hack up whatever build system the project itself uses, we internally have a script that wraps `clang`, and we set the build system to use our script as its "compiler".  Whenever the build system invokes our script to "compile" something, we first generate bitcode by passing along all the arguments we were invoked with plus `-emit-llvm`, and then we perform the actual compile command that was requested.  (So our script invokes `clang` twice for every time it is invoked.)  I'd share the script but it's actually rather complicated and has a bunch more features that probably aren't necessary, and I'm not the author.  It should be pretty easy to write a simple bash or python script that does the bare minimum.

**Comment by dvdplm** [comment]
Thank you for your detailed response!

So for instance to run, say, constant time checks as part of CI, I'd configure the runners to `--emit=llvm-bc` and have the test check for the presence of the `.bc` files, correct? I guess one doubt I have is that the tests are often compiled in debug mode but for `haybale-pitchfork` to work its magic I'd really want the analysis to be made on the optimized code. 
Thinking out aloud here, maybe using a separate test crate that pulls in the code to test as a dependency with a different optimization level?

> our script invokes clang twice for every time it is invoked.

Not sure I understood why this is necessary; does emitting the bitcode cause the final build artifact to be slower/bigger? And if yes, is this relevant to rust code as well?

**Comment by cdisselkoen** [comment]
> I'd ... have the test check for the presence of the `.bc` files, correct?

I'm not quite sure what this is getting at, but I think the idea would be to run Pitchfork on the generated `.bc` files.  You're correct that `--emit=llvm-bc` should work to generate `.bc` files for Rust code.

> really want the analysis to be made on the optimized code.

Yes, I highly recommend this.  Both because optimizations may sometimes change the constant-time behavior of the code, and simply because the analysis will run much faster on optimized code, as there are fewer instructions and memory operations to analyze.

> our script invokes clang twice for every time it is invoked.

The script I described is only used for C/C++ build systems - it's not necessary for Rust code.  The reason we do this is because some build systems will fail early if we only generate `.bc` files - for instance, `make` will fail if the compile command doesn't actually generate the `.o` it was expecting.  The `.bc` files are only for Pitchfork, and the build system doesn't know or care that the `.bc` file was generated as a side effect of running the "compiler".

**Comment by dvdplm** [comment]
> I'm not quite sure what this is getting at,

I was trying to imagine a production pipeline that integrates this. I imagine a scenario where devs don't usually want to check for CT-ness as part of their usual workflow, but we want the CI to so. For that to work I'd need an automated setup where the CI first builds the bitcode files and then runs the CT tests on them. As tests are commonly built with different compilation settings we'd need a similar two-pass setup as you describe for the C/C++ builds you do.
I was thinking about using an ad-hoc `ct-tests` crate that pulls in the test target crate as a dependency set to compile in release mode (using the new [per-dependency override](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides)), while the tests themselves can use the default profile. 
The result would be a set of bitcode files where some are from an optimized compilation (the target) and some are not (the tests), but we'd only load the ones from the target anyway so that doesn't matter too much.
The goal would be to have a single cargo command to both generate the bitcode files and run the checks on them.

I guess one problem with that approach is that the analysis code would not be optimized, so perhaps slow.

**Comment by cdisselkoen** [comment]
This sounds on the right track to me.  I will say that it's probably worth testing whether compiling the analysis code with optimizations "pays off" the extra compile time.  Running Pitchfork without optimizations can be quite slow - even running Pitchfork _with_ optimizations can be quite slow, for some workloads, depending on the constraints placed on function parameters and the particular function hooks used etc.
